[extend]
useDefault = true

[allowlist]
description = "Ignore .env.example dev-placeholders and specific secrets from history"
paths = [
    '''(^|/)\.env(\.[^/]+)?\.example$''',
]
commits = ["214ba8fd6e150abbd3163ee14471308dab95894c", "e8cc23357aa2a436ec25788a7175568aa71dd30a"]
