// <auto-generated />
using System;
using BugShot.Api.Data;
using BugShot.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BugShot.Api.Migrations
{
    [DbContext(typeof(BugShotDbContext))]
    [Migration("20260923123502_AddLocalhostDemoOrigin")]
    partial class AddLocalhostDemoOrigin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "attachment_kind", new[] { "screenshot", "user_upload", "console_log" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_channel_type", new[] { "email", "webhook" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_delivery_status", new[] { "pending", "sending", "sent", "failed", "throttled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_event_type", new[] { "ticket_created", "comment_added", "status_changed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "project_role", new[] { "viewer", "member", "maintainer" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ticket_status", new[] { "new", "in_progress", "resolved", "rejected", "deleted" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_token_purpose", new[] { "invitation", "password_reset" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BugShot.Api.Models.NotificationChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email_address");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int?>("ThrottleMaxEvents")
                        .HasColumnType("integer")
                        .HasColumnName("throttle_max_events");

                    b.Property<int?>("ThrottleWindowSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("throttle_window_seconds");

                    b.Property<NotificationChannelType>("Type")
                        .HasColumnType("notification_channel_type")
                        .HasColumnName("type");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("webhook_secret");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id")
                        .HasName("pk_notification_channels");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_notification_channels_project_id");

                    b.ToTable("notification_channels", (string)null);
                });

            modelBuilder.Entity("BugShot.Api.Models.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<NotificationEventType>("EventType")
                        .HasColumnType("notification_event_type")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RenderedBody")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("rendered_body");

                    b.Property<string>("RenderedSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rendered_subject");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<NotificationDeliveryStatus>("Status")
                        .HasColumnType("notification_delivery_status")
                        .HasColumnName("status");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_deliveries");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_notification_deliveries_project_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_notification_deliveries_ticket_id");

                    b.HasIndex("ChannelId", "CreatedAt")
                        .HasDatabaseName("ix_notification_deliveries_channel_id_created_at");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_notification_deliveries_status_next_attempt_at");

                    b.ToTable("notification_deliveries", (string)null);
                });

            modelBuilder.Entity("BugShot.Api.Models.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<NotificationChannelType>("ChannelType")
                        .HasColumnType("notification_channel_type")
                        .HasColumnName("channel_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<NotificationEventType>("EventType")
                        .HasColumnType("notification_event_type")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_notification_templates");

                    b.HasIndex("EventType", "ChannelType")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_templates_event_type_channel_type")
                        .HasFilter("project_id IS NULL");

                    b.HasIndex("ProjectId", "EventType", "ChannelType")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_templates_project_id_event_type_channel_type")
                        .HasFilter("project_id IS NOT NULL");

                    b.ToTable("notification_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Body = "{{ticket.description}}",
                            ChannelType = NotificationChannelType.Email,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventType = NotificationEventType.TicketCreated,
                            Subject = "[{{project.name}}] New ticket {{ticket.id}}"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Body = "{{ticket.description}}",
                            ChannelType = NotificationChannelType.Webhook,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventType = NotificationEventType.TicketCreated
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Body = "{{comment.author}}: {{comment.body}}",
                            ChannelType = NotificationChannelType.Email,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventType = NotificationEventType.CommentAdded,
                            Subject = "[{{project.name}}] New comment on {{ticket.id}}"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Body = "{{comment.author}}: {{comment.body}}",
                            ChannelType = NotificationChannelType.Webhook,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventType = NotificationEventType.CommentAdded
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Body = "{{status.from}} -> {{status.to}}",
                            ChannelType = NotificationChannelType.Email,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventType = NotificationEventType.StatusChanged,
                            Subject = "[{{project.name}}] Status changed for {{ticket.id}}"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Body = "{{status.from}} -> {{status.to}}",
                            ChannelType = NotificationChannelType.Webhook,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventType = NotificationEventType.StatusChanged
                        });
                });

            modelBuilder.Entity("BugShot.Api.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_key");

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Key = "demo",
                            Name = "Projekt demo"
                        });
                });

            modelBuilder.Entity("BugShot.Api.Models.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<ProjectRole>("Role")
                        .HasColumnType("project_role")
                        .HasColumnName("role");

                    b.HasKey("ProjectId", "UserId")
                        .HasName("pk_project_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_members_user_id");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("BugShot.Api.Models.ProjectOrigin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("origin");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_project_origins");

                    b.HasIndex("ProjectId", "Origin")
                        .IsUnique()
                        .HasDatabaseName("ix_project_origins_project_id_origin");

                    b.ToTable("project_origins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Origin = "http://127.0.0.1:5500",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            Origin = "http://localhost:5500",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("BugShot.Api.Models.SanitizationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("field_name");

                    b.Property<int>("MatchCount")
                        .HasColumnType("integer")
                        .HasColumnName("match_count");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_sanitization_logs");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_sanitization_logs_rule_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_sanitization_logs_ticket_id");

                    b.ToTable("sanitization_logs", (string)null);
                });

            modelBuilder.Entity("BugShot.Api.Models.SanitizationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("pattern");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Replacement")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replacement");

                    b.HasKey("Id")
                        .HasName("pk_sanitization_rules");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_sanitization_rules_project_id");

                    b.ToTable("sanitization_rules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Pattern = "(?<![\\w.+-])[\\w.+-]+@[\\w-]+(?:\\.[\\w-]+)+",
                            Replacement = "***"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Pattern = "(?i)\"?\\b(password|passwd|pwd)\"?\\s*[:=]\\s*\"?[^\"'\\r\\n,\\s}]+\"?",
                            Replacement = "***"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Pattern = "(?i)\"?\\b(login|username|user_name)\"?\\s*[:=]\\s*\"?[^\"'\\r\\n,\\s}]+\"?",
                            Replacement = "***"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Pattern = "(?i)(\\bAuthorization\\s*:\\s*(?:Bearer|Digest)\\s+)\\S+",
                            Replacement = "$1***"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Pattern = "(?i)(\\bAuthorization\\s*:\\s*Basic\\s+)\\S+",
                            Replacement = "$1***"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Pattern = "(?i)\"?\\b(?:access_token|refresh_token|id_token|session_id|sessionId)\"?\\s*[:=]\\s*\"?[^\"'\\r\\n,\\s}]+\"?",
                            Replacement = "***"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Pattern = "(?i)\"?\\b(?:api[_-]?key|x-api-key|client[_-]?secret|x-client-secret|api[_-]?secret)\"?\\s*[:=]\\s*\"?[^\"'\\r\\n,\\s}]+\"?",
                            Replacement = "***"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Pattern = "(?i)\"?\\b(?:csrf[_-]?token|xsrf[_-]?token|x-csrf-token|x-xsrf-token)\"?\\s*[:=]\\s*\"?[^\"'\\r\\n,\\s}]+\"?",
                            Replacement = "***"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Pattern = "(?i)(\\bCookie\\s*:\\s*)[^\\r\\n]+",
                            Replacement = "$1***"
                        });
                });

            modelBuilder.Entity("BugShot.Api.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BrowserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("browser_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("description");

                    b.Property<double?>("DevicePixelRatio")
                        .HasColumnType("double precision")
                        .HasColumnName("device_pixel_ratio");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("device_type");

                    b.Property<string>("Language")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("language");

                    b.Property<string>("OsName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("os_name");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("page");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("page_url");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateTimeOffset?>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<TicketStatus>("Status")
                        .HasColumnType("ticket_status")
                        .HasColumnName("status");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<int?>("ViewportHeight")
                        .HasColumnType("integer")
                        .HasColumnName("viewport_height");

                    b.Property<int?>("ViewportWidth")
                        .HasColumnType("integer")
                        .HasColumnName("viewport_width");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("ProjectId", "ReceivedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_tickets_project_id_received_at");

                    b.HasIndex("ProjectId", "Status", "ReportedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_tickets_project_id_status_reported_at");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("BugShot.Api.Models.TicketAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<AttachmentKind>("Kind")
                        .HasColumnType("attachment_kind")
                        .HasColumnName("kind");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("uri");

                    b.HasKey("Id")
                        .HasName("pk_ticket_attachments");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_ticket_attachments_ticket_id");

                    b.ToTable("ticket_attachments", (string)null);
                });

            modelBuilder.Entity("BugShot.Api.Models.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("author");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_comments");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("ix_ticket_comments_ticket_id_created_at");

                    b.ToTable("ticket_comments", (string)null);
                });

            modelBuilder.Entity("BugShot.Api.Models.TicketStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("changed_by");

                    b.Property<TicketStatus>("FromStatus")
                        .HasColumnType("ticket_status")
                        .HasColumnName("from_status");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<TicketStatus>("ToStatus")
                        .HasColumnType("ticket_status")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_ticket_status_changes");

                    b.HasIndex("TicketId", "ChangedAt")
                        .HasDatabaseName("ix_ticket_status_changes_ticket_id_changed_at");

                    b.ToTable("ticket_status_changes", (string)null);
                });

            modelBuilder.Entity("BugShot.Api.Models.TicketUploadToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_ticket_upload_tokens");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_ticket_upload_tokens_ticket_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_upload_tokens_token_hash");

                    b.ToTable("ticket_upload_tokens", (string)null);
                });

            modelBuilder.Entity("BugShot.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BugShot.Api.Models.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_refresh_tokens_user_id");

                    b.ToTable("user_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("BugShot.Api.Models.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<UserTokenPurpose>("Purpose")
                        .HasColumnType("user_token_purpose")
                        .HasColumnName("purpose");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_tokens_user_id");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("BugShot.Api.Models.NotificationChannel", b =>
                {
                    b.HasOne("BugShot.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_channels_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BugShot.Api.Models.NotificationDelivery", b =>
                {
                    b.HasOne("BugShot.Api.Models.NotificationChannel", "Channel")
                        .WithMany("Deliveries")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_deliveries_notification_channels_channel_id");

                    b.HasOne("BugShot.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_deliveries_projects_project_id");

                    b.HasOne("BugShot.Api.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_deliveries_tickets_ticket_id");

                    b.Navigation("Channel");

                    b.Navigation("Project");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BugShot.Api.Models.NotificationTemplate", b =>
                {
                    b.HasOne("BugShot.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notification_templates_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BugShot.Api.Models.ProjectMember", b =>
                {
                    b.HasOne("BugShot.Api.Models.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects_project_id");

                    b.HasOne("BugShot.Api.Models.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_users_user_id");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BugShot.Api.Models.ProjectOrigin", b =>
                {
                    b.HasOne("BugShot.Api.Models.Project", "Project")
                        .WithMany("Origins")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_origins_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BugShot.Api.Models.SanitizationLog", b =>
                {
                    b.HasOne("BugShot.Api.Models.SanitizationRule", "Rule")
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sanitization_logs_sanitization_rules_rule_id");

                    b.HasOne("BugShot.Api.Models.Ticket", "Ticket")
                        .WithMany("SanitizationLogs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sanitization_logs_tickets_ticket_id");

                    b.Navigation("Rule");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BugShot.Api.Models.SanitizationRule", b =>
                {
                    b.HasOne("BugShot.Api.Models.Project", "Project")
                        .WithMany("SanitizationRules")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_sanitization_rules_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BugShot.Api.Models.Ticket", b =>
                {
                    b.HasOne("BugShot.Api.Models.Project", "Project")
                        .WithMany("Tickets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BugShot.Api.Models.TicketAttachment", b =>
                {
                    b.HasOne("BugShot.Api.Models.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_attachments_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BugShot.Api.Models.TicketComment", b =>
                {
                    b.HasOne("BugShot.Api.Models.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_comments_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BugShot.Api.Models.TicketStatusChange", b =>
                {
                    b.HasOne("BugShot.Api.Models.Ticket", "Ticket")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_status_changes_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BugShot.Api.Models.TicketUploadToken", b =>
                {
                    b.HasOne("BugShot.Api.Models.Ticket", "Ticket")
                        .WithMany("UploadTokens")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_upload_tokens_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BugShot.Api.Models.UserRefreshToken", b =>
                {
                    b.HasOne("BugShot.Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BugShot.Api.Models.UserToken", b =>
                {
                    b.HasOne("BugShot.Api.Models.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BugShot.Api.Models.NotificationChannel", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("BugShot.Api.Models.Project", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Origins");

                    b.Navigation("SanitizationRules");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("BugShot.Api.Models.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("SanitizationLogs");

                    b.Navigation("StatusHistory");

                    b.Navigation("UploadTokens");
                });

            modelBuilder.Entity("BugShot.Api.Models.User", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
